name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
       registry: ghcr.io
       username: ${{ github.repository_owner }}
       password: ${{ secrets.GHCR_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push to ghcr
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        platforms: linux/amd64
        push: true
        tags: ghcr.io/bbusse/swayvnc:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
